### ISSUE TITLE
 Connection Request Timed out.

### ISSUE THREAD

**Issue by senzacionale** [nats-io/stan.net#108]
Exception

> {STAN.Client.StanConnectRequestTimeoutException: Connection Request Timed out.
>    at STAN.Client.Connection..ctor(String stanClusterID, String clientID, StanOptions options)
>    at STAN.Client.StanConnectionFactory.CreateConnection(String clusterID, String clientID, StanOptions options)

I have wery simple scenario:
```

string url = "nats://127.0.0.1:4222";
            string clientID = "test-client";
            string clusterID = "test-cluster";

            var opt = StanOptions.GetDefaultOptions();
            opt.NatsURL = url;
            var cf = new StanConnectionFactory();
            using (var c = cf.CreateConnection(clusterID, clientID, opt))
            {
                c.Publish(Subject, ObjectToByteArray(command));
            }
```

and I am starting server as `"nats-streaming-server.exe"
`
> 
> [19876] 2019/04/12 22:34:19.468122 [[32mINF[0m] STREAM: Starting nats-streaming-server[test-cluster] version 0.12.2
> [19876] 2019/04/12 22:34:19.470122 [[32mINF[0m] STREAM: ServerID: A7cAW2Grx60dK2ASZ2Plj6
> [19876] 2019/04/12 22:34:19.470122 [[32mINF[0m] STREAM: Go version: go1.11.6
> [19876] 2019/04/12 22:34:19.471123 [[32mINF[0m] STREAM: Git commit: [not set]
> [19876] 2019/04/12 22:34:19.472123 [[32mINF[0m] Starting nats-server version 1.4.1
> [19876] 2019/04/12 22:34:19.472123 [[32mINF[0m] Git commit [not set]
> [19876] 2019/04/12 22:34:19.474123 [[32mINF[0m] Listening for client connections on 0.0.0.0:4222
> [19876] 2019/04/12 22:34:19.474123 [[32mINF[0m] Server is ready
> [19876] 2019/04/12 22:34:19.532121 [[32mINF[0m] STREAM: Recovering the state...
> [19876] 2019/04/12 22:34:19.533123 [[32mINF[0m] STREAM: No recovered state
> [19876] 2019/04/12 22:34:19.784123 [[32mINF[0m] STREAM: Message store is MEMORY
> [19876] 2019/04/12 22:34:19.784123 [[32mINF[0m] STREAM: ---------- Store Limits ----------
> [19876] 2019/04/12 22:34:19.786121 [[32mINF[0m] STREAM: Channels:                  100 *
> [19876] 2019/04/12 22:34:19.787121 [[32mINF[0m] STREAM: --------- Channels Limits --------
> [19876] 2019/04/12 22:34:19.788121 [[32mINF[0m] STREAM:   Subscriptions:          1000 *
> [19876] 2019/04/12 22:34:19.789122 [[32mINF[0m] STREAM:   Messages     :       1000000 *
> [19876] 2019/04/12 22:34:19.789122 [[32mINF[0m] STREAM:   Bytes        :     976.56 MB *
> [19876] 2019/04/12 22:34:19.790122 [[32mINF[0m] STREAM:   Age          :     unlimited *
> [19876] 2019/04/12 22:34:19.791121 [[32mINF[0m] STREAM:   Inactivity   :     unlimited *
> [19876] 2019/04/12 22:34:19.792121 [[32mINF[0m] STREAM: ----------------------------------

What can be wrong. It is very simple scenario and should work

**Comment by ColinSullivan1** [comment]
@senzacionale , This looks like it should work if your client is on the same machine as the server.  You can check basic connectivity if you telnet to the NATS streaming server from where your client is running.

e.g. 
```bash
$ telnet 127.0.0.1 4222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"EbtYzmZr3y9F1LWhfMAdNT","version":"1.3.0","proto":1,"go":"go1.11.2","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":4} 
```
If you don't see this, you have some other connectivity issues or will want to try using the hostname/IP of the machine the NATS streaming server is running on in your client.

**Comment by senzacionale** [comment]
I see the same as you. I figure out that in single thread everything is working. Can be problem with multithreading because I want to use nats streaming inside websocket events. Is nats streaming thread safe and support multithreading?

**Comment by ColinSullivan1** [comment]
The NATS streaming is thread-safe...  Would you have a test application that is failing so I can reproduce this issue?

**Comment by ColinSullivan1** [comment]
Thanks again for raising this issue. I'm closing it due to inactivity.  Please feel free to re-open if you get back to this.
