### ISSUE TITLE
Messages get redelivered even if subscriber handler takes less than AckWait

### ISSUE THREAD

**Issue by livrgst** [nats-io/stan.net#110]
The issue can be reproduced in the subscriber [example](https://github.com/nats-io/csharp-nats-streaming/blob/master/examples/stan-sub/stan-sub.cs) if a small delay (like 100ms) is introduced:

```csharp
            EventHandler<StanMsgHandlerArgs> msgHandler = (sender, args) =>
            {
                if (received == 0)
                    sw.Start();

                received++;

                if (verbose)
                {
                    Console.WriteLine("Received seq # {0}: {1}",
                        args.Message.Sequence,
                        System.Text.Encoding.UTF8.GetString(args.Message.Data));
                }

                Thread.Sleep(100);

                if (received >= count)
                {
                    sw.Stop();
                    ev.Set();
                }
            };
```
Even if the handler processing is much shorter than the default subscription AckWait time of 30s, a large part of the messages (2000-3000 out of 10000) get redelivered, some of them up to 8 times. 

If the AckWait time is reduced to 1s the redelivered message are much more frequent and the program terminates with NATSSlowConsumerException. The issue does not appear if the thread sleep is not present in the message handler.

As a mention, for the nats server we use nats-streaming:0.12.2

**Comment by ColinSullivan1** [comment]
The default ackWait time was incorrect - #117 should address this issue. 

In the meantime,  you can manually set your [AckWait](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_subscription_options.html#a345ca6a37db6c5ab84c0b2cdac66688e) timeout to 30s.  Also, if you reduce your [MaxInflight](http://nats-io.github.io/csharp-nats-streaming/class_s_t_a_n_1_1_client_1_1_stan_subscription_options.html#ad5e104db7d237d5b515642971ae62cfb) you'll clear this up as well; the server will suspend sending until your app acknowledges enough messages reducing the # of buffered messages and likelyhood they'll timeout while waiting to be processed.

Do these clear up your issue?

**Comment by ColinSullivan1** [comment]
I'm going to close this.  If you continue to encounter this problem, please reopen this issue.

**Comment by lghinet** [comment]
that solved the issue, thanks
