### ISSUE TITLE
Invalid uri exception on multiple server list.

### ISSUE THREAD

**Issue by sujitn** [nats-io/stan.net#124]
Throws an Invalid uri exception if nats url contains multiple server separated by comma

The issue occurs on StanConnection.cs, new ConnectionFactory().CreateConnection(nopts) doesnt process the url string.

**Comment by sujitn** [comment]
Fixed in #125

**Comment by ColinSullivan1** [comment]
This fix has been released with NATS version 0.9.0, and is available on Nuget.  Thank you for your contribution!

**Comment by DeployChef** [comment]
Thanks!
