### ISSUE TITLE
Recommended Pattern when Using IStanConnection

### ISSUE THREAD

**Issue by robertmircea** [nats-io/stan.net#135]
I have an app which which subscribes to different subjects. Currently I am using a single IStanConnection shared by all subscriptions, but I was wondering if this is the intended usage pattern.

What is the recommended pattern for using IStanConnection: one IStanConnection shared by multiple/all subscriptions or each subscription with its own IStanConnection?

**Comment by ColinSullivan1** [comment]
@robertmircea, Thank you for using NATS!  That is the intended pattern - most users have one StanConnection for all subscriptions.  That's the preferred/recommended approach and should suffice for nearly all use cases.

In **very** rare cases we recommend multiple connections - these would be to connect to different streaming clusters or for edge case performance reasons.  If that's your case certainly let us know and we'll be happy to help you design and tune for that.

**Comment by ColinSullivan1** [comment]
@robertmircea , certainly feel free to re-open if you have any more questions.
