### ISSUE TITLE
Infinite loop after NATS restart

### ISSUE THREAD

**Issue by kaspertygesen** [nats-io/stan.net#137]
We experience high CPU load in our services after NATS gets restarted or crashes for some reason.
It seems like there is an infinite loop somewhere in the `STAN.CLIENT`.

We have profiled it and it seems like the issue is related to this:

```
instance bool [STAN.CLIENT] STAN.Client.BlockingDictionary`2[System.__Canon,System.__Canon]::Remove(!0,!1&,int32)
instance class STAN.Client.PublishAck [STAN.CLIENT] STAN.Client.Connection::removeAck(string)
instance void [STAN.CLIENT] STAN.Client.PublishAck::ackTimerCb(object)
```

After a quick view of the code this snippet might be the issue when `0` is passed to `BlockingDictionary.Remove()` as timeout from `removeAck()`.

```
while (d.Count == 0)
{
    if (timeout < 0)
    {
        Monitor.Wait(dLock);
    }
    else
    {
        if (timeout > 0)
        {
            if (Monitor.Wait(dLock, timeout) == false)
            {
                throw new Exception("timeout");
            }
        }
    }
}
```

To reproduce it I do the following: (It doesn't happen every time)

- Crash NATS 
   - I do this by sending a message which is too large for the MySQL data field. This was the reason we encountered the problem in the first place.
- Restart NATS
- Send a message to NATS through the STAN.CLIENT
- Inspect the docker container for high CPU usage

Let me know if I need to provide a repository for reproducing this issue. I hope it's not nessesary :-)

![image](https://user-images.githubusercontent.com/15162527/64528788-a224d500-d309-11e9-91d0-214fce52961a.png)

**Comment by ColinSullivan1** [comment]
@kaspertygesen , thank you for raising this issue, and I do think you've found the bug with the timeout - this is related to #136.  I'll take a look at it today and get a fix out as a soon as I can.  Thanks!

**Comment by ColinSullivan1** [comment]
FYI - I've found the issue, and have a fix but it's not ideal imo.  I want to clean up some of the code around publish ack processing to keep this clean.  I'm hoping to have something tomorrow.

**Comment by ColinSullivan1** [comment]
FYI - Just checked in a fix into master.  This one should be fixed given the results of the new tests but if you'd like to give it a shot to confirm I'd be grateful.

**Comment by kaspertygesen** [comment]
I have not been able to reproduce the problem with the new code. I have run the scenario several times.
I would consider the problem resolved 👍 

There is still a minor performance issue when NATS crashes, where the services run high on CPU, but they recover automatically within a minute or so.
I have tried to profile it, but the trace doesn't give me anything useful, it just points to some messaging library in the Linux kernel. I am not sure whether it has anything to do with the STAN.Client or not.
I don't have any easy way to reproduce it, sorry.

**Comment by ColinSullivan1** [comment]
Good to hear!  Thank you for testing, much appreciated!

If you do get more information about your performance issue or can isolate a test case please open an issue...
