### ISSUE TITLE
When wait 1.7 version?

### ISSUE THREAD

**Issue by DeployChef** [nats-io/stan.net#140]
When wait 1.7 version with reconnect changes?

**Comment by ColinSullivan1** [comment]
@DeployChef , I will try for today.  I was waiting for some feedback on the reconnect issue - we've verified it's fixed by someone else reporting the issue so will proceed with the release.

**Comment by ColinSullivan1** [comment]
I've just published a release.  It may take awhile for Nuget to index.

Here you go:  https://www.nuget.org/packages/STAN.Client/0.1.7

**Comment by DeployChef** [comment]
Wow thanks! Have a nice one!
