### ISSUE TITLE
Setup pendinglimits with options.

### ISSUE THREAD

**Issue by alexpantyukhin** [nats-io/stan.net#146]
Pendinglimits are hardcoded there https://github.com/nats-io/stan.net/blob/master/src/STAN.Client/StanConnection.cs#L281 . 
Is it okay to add new parameters into `StanOptions`?

**Comment by alexpantyukhin** [comment]
It's okay for me to create a PR, if the issue is approved.

**Comment by ColinSullivan1** [comment]
I'd appreciate that!  I'd suggest a method:
```csharp
        /// <summary>
        /// Sets the limits for pending publish acknowledgement messages and bytes.
        /// </summary>
        /// <remarks>Zero (<c>0</c>) is not allowed. Negative values indicate that the
        /// given metric is not limited.</remarks>
        /// <param name="messageLimit">The maximum number of pending messages.</param>
        /// <param name="bytesLimit">The maximum number of pending bytes of payload.</param>
       StanOptions.SetPubAckPendingLimits(int messageLimit, int bytesLimit);
```

**Comment by alexpantyukhin** [comment]
@ColinSullivan1 Do youthink the method would be better? I reviewed the `Options`class and found that there mostly properties: https://github.com/nats-io/stan.net/blob/master/src/STAN.Client/Options.cs#L21

**Comment by ColinSullivan1** [comment]
I do because you'd likely want to set both message and bytes limits at the same time to reduce the chance of error.

**Comment by danielwertheim** [comment]
@alexpantyukhin added support for this in PR #161 That will solve your needs, right?
