### ISSUE TITLE
Add support for IObservable in the STAN client

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/stan.net#147]
Add support for `IObservable<>` as we did with the `NATS.Net` client (https://github.com/nats-io/nats.net/issues/303), but extend only the `IStanConnection` as the subscription does not expose the event handler etc.

Build on top of the RX parts introduced in NATS, e.g. `NATSObservable`

**Comment by danielwertheim** [comment]
@ColinSullivan1 I have a branch (https://github.com/nats-io/stan.net/compare/master...danielwertheim:rx) were this is implemented, but as it builds upon stuff in the NATS-client that has not been released yet, there no point in opening a PR as the build will fail. 

We need to get at least a preview release out of NATS, so that STAN can use some RX parts in it.

**Comment by ColinSullivan1** [comment]
Ok.  Let's get a release of NATS out with RX then.  I'll update the deploy keys right now.
