### ISSUE TITLE
Question: lifetime & thread safety

### ISSUE THREAD

**Issue by jdvor** [nats-io/stan.net#149]
For a long running process (daemon or windows service) what are recommended / expected  lifetime for objects like `StanConnectionFactory`, `Connection` and `AsyncSubscription`?
Also, are they thread-safe?

From a brief glance to the source code, I would say:
- `StanConnectionFactory`: does not matter
-  `Connection`, `AsyncSubscription`: re-usable, long-lived and probably thread-safe objects

Could you confirm it is indeed so or - if not - I'd be grateful for some basic guidelines for these objects.

**Comment by ColinSullivan1** [comment]
@jdvor , Thanks for using NATS!  Yes, they are longer lived objects and both are thread-safe.  Every connection and subscription creates resources on the server, so if you have a choice, better to keep them around for as long as you need them.  That being said, if you know you won't require a connection or subscription for a long period of time, then don't worry about recreating connections or subscriptions.  `Long periods of time` is subjective - it varies based on your use case and number of concurrent clients -  just try to avoid unnecessarily stressing the server with new connections or subscriptions.

**Comment by jdvor** [comment]
Thanks very much.
