### ISSUE TITLE
NATS.Client v0.10.0+ is signed

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/stan.net#152]
As of v0.10.0 of NATS.Client (that STAN.Client is dependent on), NATS.Client.dll is once again signed. This causes issues as you then e.g. can not have the current version of STAN.Client and force update to v0.10.0 of NATS.Client

**Solution 1:** Release a new version of STAN.Net that is signed and takes a dependency on v0.10.0 of NATS.Client

**Solution 2:** Release a new version of STAN.Client and NATS.Client that is not signed then release one STAN.Client.Signed and NATS.Client.Signed

**Comment by danielwertheim** [comment]
@ColinSullivan1 here's the issue for signing in NATS.Client https://github.com/nats-io/nats.net/issues/291

**Comment by danielwertheim** [comment]
Solution 1 would be solved with PR #150

**Comment by ColinSullivan1** [comment]
imo go with solution #1.  Long term we'll be moving to JetStream so I think releasing streaming releases solely for critical .NET core fixes is acceptable.
