### ISSUE TITLE
Scaling a Subscriber

### ISSUE THREAD

**Issue by cwoolum** [nats-io/stan.net#160]
I am just looking into the use of NATS in my services and I had a question about some functionality. 

I have a bunch of messages that get dumped into the queue in large numbers. I have a single subscriber that needs to scale to accommodate load up to a certain n number of max instances. 

Based on my research, it seems that every instance of my service that subscribes would receive each message which would make the scaling useless. Would I be able to use durable subscriptions to handle this? 

I definitely want at-least-once delivery and can handle the messages being processed multiple times. I just don't want every message to be processed by every subscriber.

**Comment by ColinSullivan1** [comment]
@cwoolum, You can scale with load balanced queue subscribers.

When you create a queue subscriber by assigning a queue group name, the NATS streaming server will send messages to the subscriber in the group with the least number of outstanding acknowledgements (usually the "least busy" client).  All you need to do is launch additional instances of your application/service and NATS will load balance between them.

The API to include a queue group name can be found here [here](http://nats-io.github.io/stan.net/interface_s_t_a_n_1_1_client_1_1_i_stan_connection.html#a04d9a7370dd48e8ca7f9db3c6d8a8cbc), and the load balanced queue subscriber pattern is described [here](https://docs.nats.io/nats-streaming-concepts/channels/subscriptions/queue-group).

**Comment by cwoolum** [comment]
Thanks! That's exactly what I was looking for!

**Comment by ColinSullivan1** [comment]
Absolutely - thanks for using NATS!
