### ISSUE TITLE
Consumer does not process message after changing clientId

### ISSUE THREAD

**Issue by minhhungit** [nats-io/stan.net#171]
As title, consumer will not process message anymore after changing clientId although we are using -all mode

- windows
- nats-streaming-server-v0.16.2-windows-amd64
- consumer command:
> .\StanSub -qgroup newgroup -clientid xyz -all

---

I added video for reproducing 

[issue-with-client-id.zip](https://github.com/nats-io/stan.net/files/4021407/issue-with-client-id.zip)

**Comment by ColinSullivan1** [comment]
I was able to reproduce this and will take a look.

**Comment by ColinSullivan1** [comment]
@minhhungit , This was an issue of the sample application not cleanup up between test runs.  The connection and subscription was left "active" between test runs so the streaming server was not redelivering the messages.  I have a PR updating the sample code to cleanup on early exit.

You'll want to add a [Console.CancelKeyPress](https://github.com/nats-io/stan.net/pull/172/files#diff-6e65203e4fa98aa6e93b87199e0df9b2R71) event handler in your test application that closes the connection, and if applicable, unsubscribes the durable.  An example can be found [here](https://github.com/nats-io/stan.net/pull/172/files#diff-6e65203e4fa98aa6e93b87199e0df9b2R240).

**Comment by minhhungit** [comment]
@ColinSullivan1 thank you for looking this issue

Currently I see it works well with this command:
>.\StanSub -qgroup newgroup -clientid xyz -all

But when I remove `-all`/`-seq` then it won't process message
It also does not process message when I add `durable` param like this

>.\StanSub -qgroup groupA -clientid xyz -all -durable aaaa

In another hand, when I used param `-last` it just show the last message which is processed before but does not process the rest messages are still in streams

**Comment by minhhungit** [comment]
Honestly I am not sure how `durable` work and how it interacts with other command like -all, -seq, -last

I also upload video for issue demo

[issues-with-nats-client.zip](https://github.com/nats-io/stan.net/files/4033464/issues-with-nats-client.zip)
