### ISSUE TITLE
100% CPU load once subscribed

### ISSUE THREAD

**Issue by ld100** [nats-io/stan.net#201]
I've implemented NATS Streaming subscription as a .NET core BackgroundService. Subscription is working as I see, however the app is getting 100% CPU load all the time it runs, even when there is no processing of the messages at all.

I've attached my example: https://gist.github.com/ld100/ffede4e1d6f08bf2cb089b1721a8d7bb

The only other suspicious thing I see is that every time I restart the app, it tells me a new message on the subscription arrived, while I clearly see the messages is the one already processed.

Any ideas what is wrong here?
Before C# I worked with NATS Streaming from Ruby and Go, which had much better client documentation. So I suspect I might have implemented something wrong, since the doc is too shallow this time.

**Comment by danielwertheim** [comment]
As far as I can tell, the await you do is just on setting up the subscription. Then you enter a tight loop:

```csharp
while (!stoppingToken.IsCancellationRequested)
  {
  }
```
I might have interpreted it wrong, if not, that loop will spin like crazy, right? Shouldn't it just setup the subscription and store away any resources that might need to be disposed later on?

**Comment by SuheylZ** [comment]
That is wrong way and definitely results in 100% CPU consumption. 
The right way is
```

  static private Task PrepareQuitter(Action action, CancellationToken stoppingToken)
   {
       var tcs = new TaskCompletionSource<bool>();

          stoppingToken.Register(()=> {
               action(); 
               tcs.SetResult(true);
            });

      return tcs.Task;
   }


 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation("Starting ConfigurationChangedSubscription worker at: {time}", DateTimeOffset.Now);
            var opts = StanSubscriptionOptions.GetDefaultOptions();
            opts.StartWithLastReceived();


        
            var subscription = await Task.Run(() => _stanConnection.Subscribe(Topic, opts, async (obj, args) =>
            {
                try
                {
                    _logger.LogInformation("Received a message on {subject} at {time}", args.Message.Subject, DateTimeOffset.Now);
                }
                catch (Exception ex)
                {
                    _errorTracker.Track(ex);
                    _logger.LogError("Tracked error: {error}", ex.Message);
                }
            }), stoppingToken);

            var task = PrepareQuitter(()=> subscription.Dispose(), stoppingToken);

            await task;

        }
    }
```

**Comment by ld100** [comment]
Thank you @SuheylZ
That was exactly the problem and your fix did help!
