### ISSUE TITLE
Why StanConnection blocks on PublishAck delete?

### ISSUE THREAD

**Issue by Kikimora** [nats-io/stan.net#55]
I struggle with one deadlock in my software and I think NATS Streaming is to blame. ASK timeout handler removes  PublishAck object from blocking collection right before ACK finally arrives. This makes ACL processing to forever block on empty collection.

I plan to fix this by making that collection non blocking on remove. But I wonder if this is a good idea in the first place. I've spent just a few hours learning this codebase and don't want to ruin my cluster with hard to detect issues due to this changes. Hopefully somebody with better understanding of internals can tell my why 'pubAckMap' in StanConnection blocks on deletes.

Sample piece of my log file showing how whole thing ends up in a deadlock.
[02:47:26.027785 031 DBG]  STAN before publish
[02:47:26.031718 031 DBG]  STAN Locked mu
[02:47:26.032388 031 DBG]  STAN TryAdd
[02:47:26.032536 031 DBG]  STAN TryAdd DONE
[02:47:26.032737 031 DBG]  STAN after publish
[02:47:28.039002 032 DBG]  STAN Remove ackTimerCb
[02:47:28.039228 032 DBG]  STAN Remove DONE
>>> [02:47:28.470116 111 DBG]  STAN Remove processAck <<< At this point calls to 'publish' will lock forever on 'mu' object resulting in a deadlock.

**Comment by ColinSullivan1** [comment]
@Kikimora I will take a look.   Would you have some test code that demonstrates this?  Could you be hitting the `MaxPubAcksInFlight` value, which will block publish calls?

**Comment by Kikimora** [comment]
I don't know if I hit MaxPubAcksInFlight... I removed locks in delete and since then I never saw any deadlocks like this. I'm still not sure if this is a correct fix.

**Comment by ColinSullivan1** [comment]
I've been looking into this, and haven't spotted any deadlock prone code, but I certainly admit there could be one.  Will continue to look...

**Comment by Kikimora** [comment]
@ColinSullivan1 I think that deadlock might happen if ACK timeout handler removes PublishAck object from blocking collection right before ACK finally arrives. I think this is a recipe for deadlock:
- Two parallel processes (publish and timeouts) remove same object from blocking collection. 
- Remove blocks if there is no object to remove.

**Comment by ColinSullivan1** [comment]
I believe this has been address by PR #138, specifically [this](https://github.com/nats-io/stan.net/pull/138/files#diff-5066fbd80c4bc167aec5d4156f019121R77) section of code - if the Ack was removed, then the Ack complete will not be invoked through `InvokeHandler`.  Please re-open if you discover this in a release after v0.1.6.
